CREATE TABLE IF NOT EXISTS corporates (

    id SERIAL PRIMARY KEY,

    corporate_code VARCHAR(20) NOT NULL UNIQUE,

    corporate_name VARCHAR(100) NOT NULL UNIQUE,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);